# 1 Lineare Ausgleichsrechnung mit Hilfe der QR-Zerlegung

## Einführende Fragen

1. Wie lautet 𝑄,𝑅 so, dass 𝐴=𝑄·𝑅 gilt?

    𝑄 ist orthogonal, und 𝑅 eine reguläre obere rechte Dreiecksmatrix
    $$ Rx = Q^T b $$
    
    
2. Welche Dimension hat 𝑄, 𝑅?

    𝑄, 𝑅 weisen folgende Dimensionen auf:
    $$ Q_{red} \in \mathbb{R}^{n \times n} , R \in \mathbb{R}^{n \times n} $$
    
    
    
3. Welche Dimension hat das reduzierte Problem?

    Das reduzierte Problem hat die Dimensionen:
    $$ Q_{red} \in \mathbb{R}^{m \times n} , R \in \mathbb{R}^{n \times n} $$
    
    
4. Warum reichen die reduzierten Matrizen 𝑄, 𝑅?

    Die reduzierten Matrizen reichen, weil die Nullzeilen weggelassen werden können.

## Implementation der QR-Zerlegung:
Mithilfe jupyter notebook zur Householder Transformation.

In [65]:
import numpy as np
from numpy.linalg import norm

# Definition des Kronecker Deltas
def mykron(x):
    res = np.zeros([len(x),len(x)], dtype=float) # Matrix initialisieren
    for i in range(len(x)):
        res[:,i] = x * x[i]
    return(res)

# Definition der Householder Transformation
def HouseholderTransformation(w):    
    res=np.eye(len(w)) - (2* mykron(w)/(np.dot(w,w)))
    return(res)

# Neudefinition der sign funktion, weil numpy sign liefert 0 für 0
def mysign(x): 
    if x >= 0:
        return 1
    else:
        return -1

# Definition der Hyperebene  𝑤 = 𝑦 + sign(𝑦1)‖𝑦‖2𝑒1
def hyp(A,y):
    y=A[k:,k]
    return y+mysign(y[0])*np.linalg.norm(y)*e(len(y))

# Definiton des Einheitsvektors
def e(n):
    return np.array([1]+[0 for k in range(n-1)])

# Beispielmatrix
A = np.array([[-1,  7, -8, -9,  6],
       [-6, -8,  0,  3,  8],
       [-4, -2,  8,  0, -2],
       [-1, -9,  4, -8,  2],
       [-3, -5, -5,  7, -4],
       [-7, -4,  7, -1,  5],
       [-9, -7,  6, -5, -8],
       [-4, -3, -5,  3, -6],
       [ 5,  7,  5, -4, -5],
       [ 4, -6, -8, -2, -5]],dtype=float)
m,n = A.shape

# Householder Transformation an der Matrix A ausführen
A1 = A
Q = np.zeros([m,m], dtype=float) # Matrix Q initialisieren
for k in range(0,n):
    w = hyp(A1,k)
    Qk = HouseholderTransformation(w)
    A1[k:,k:] = Qk@A1[k:,k:]
    print(Q)
    print(Qk)
    
    Q= Qk*Q
    print(Q)

# Matrix A1 nach der Householder Transformation ausgeben
print(np.round(A1,4))

# Matrix R aus A1 rausholen
R = A1
for i in range(n,m):
    R = np.delete(R,(n), axis = 0)
print(np.round(R,4))


# Matrix Q berechnen gemäss Formel aus Skript:  Q = (Qn · ... · Q1)T = QT1 · ... · QTn


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[-0.06324555 -0.37947332 -0.25298221 -0.06324555 -0.18973666 -0.44271887
  -0.56920998 -0.25298221  0.31622777  0.25298221]
 [-0.37947332  0.86456562 -0.09028959 -0.0225724  -0.06771719 -0.15800677
  -0.20315157 -0.09028959  0.11286198  0.09028959]
 [-0.25298221 -0.09028959  0.93980694 -0.01504826 -0.04514479 -0.10533785
  -0.13543438 -0.06019306  0.07524132  0.06019306]
 [-0.06324555 -0.0225724  -0.01504826  0.99623793 -0.0112862  -0.02633446
  -0.03385859 -0.01504826  0.01881033  0.01504826]
 [-0.18973666 -0.06771719 -0.04514479 -0.0112862   0.96614141 -0.07900339
  -0.10157578 -0.04514479  0.05643099  0.04514479]
 [-0.44271887 -0.15800677 -0.10533785 -0.026

ValueError: operands could not be broadcast together with shapes (9,9) (10,10) 