# 1 Lineare Ausgleichsrechnung mit Hilfe der QR-Zerlegung

## Einführende Fragen

1. Wie lautet 𝑄,𝑅 so, dass 𝐴=𝑄·𝑅 gilt?

    𝑄 ist orthogonal, und 𝑅 eine reguläre obere rechte Dreiecksmatrix
    $$ Rx = Q^T b $$
    
    
2. Welche Dimension hat 𝑄, 𝑅?

    𝑄, 𝑅 weisen folgende Dimensionen auf:
    $$ Q_{red} \in \mathbb{R}^{n \times n} , R \in \mathbb{R}^{n \times n} $$
    
    
    
3. Welche Dimension hat das reduzierte Problem?

    Das reduzierte Problem hat die Dimensionen:
    $$ Q_{red} \in \mathbb{R}^{m \times n} , R \in \mathbb{R}^{n \times n} $$
    
    
4. Warum reichen die reduzierten Matrizen 𝑄, 𝑅?

    Die reduzierten Matrizen reichen, weil die Nullzeilen weggelassen werden können.

## Implementation der QR-Zerlegung:
Mithilfe jupyter notebook zur Householder Transformation.

In [90]:
import numpy as np
from numpy.linalg import norm

#Kronecker selber implementieren um Probleme mit Transponieren zu vermeiden
def Kronecker(w):
    res = np.zeros([len(w),len(w)],dtype=float)
    for i in range(len(w)):
        res[:,i] = w * w[i]
    return(res)

#Householder transformation implementieren 
def HouseholderTransformation(w):
    H = np.eye(len(w)) - (Kronecker(w) / (0.5 * np.dot(w,w)))
    return H

#mysign Funktion definieren da bei 0 auch 1 returned werden muss
def mysign(x): # numpy sign liefert 0 für 0
    if x >= 0:
        return 1
    else:
        return -1
    
#Einheitsvektor generieren
def e(n):
    return np.array([1]+[0 for k in range(n-1)])

#Array vorgeben
A = np.array([[-1,  7, -8, -9,  6],
       [-6, -8,  0,  3,  8],
       [-4, -2,  8,  0, -2],
       [-1, -9,  4, -8,  2],
       [-3, -5, -5,  7, -4],
       [-7, -4,  7, -1,  5],
       [-9, -7,  6, -5, -8],
       [-4, -3, -5,  3, -6],
       [ 5,  7,  5, -4, -5],
       [ 4, -6, -8, -2, -5]],dtype=float)
m,n = A.shape



# Initialisieren von Hilfsmatrizen
Anew = A.copy()
onesmax = np.eye(m)
Q = np.eye(m)

# Householder-Transformation für alle Spalten durchführen
for k in range(n):
    y = Anew[k:,k]    
    w = y.T + mysign(y[0]) * np.linalg.norm(y) * e(len(y))    
    Qk = HouseholderTransformation(w)
    Q = Q@(onesmax + np.pad(Qk,[(k,0),(k,0)]) - np.pad(np.eye(m-k),[(k,0),(k,0)]))
    Anew[k:,k:] = Qk@Anew[k:,k:]


# Überflüssigen Teil aus der R und Q Matrix wegschneiden
R = Anew[0:n]
Q = Q[0:m,0:n]
print(np.round(R,4))
print(np.round(Q,4))


# Q*R = A verifizieren, Resultat der Subtraktion Q*R-A muss 0 sein.
print(np.round(Q@R - A,4))

# Zum Verlgeich: Q und R von NumPy berechnen lassen und ausgeben
Qnp,Rnp = np.linalg.qr(A)
print(np.round(Rnp,4))
print(np.round(Qnp,4))

[[ 15.8114  11.8269  -6.5143  -0.6325  -1.2649]
 [ -0.      15.5603   1.4167  -1.8329   3.0822]
 [ -0.      -0.     -17.9877   2.92     0.9232]
 [ -0.       0.       0.      15.6753  -1.5851]
 [ -0.       0.       0.      -0.      16.8682]]
[[-6.320e-02  4.979e-01  5.069e-01 -6.129e-01  1.746e-01]
 [-3.795e-01 -2.257e-01  1.197e-01  1.274e-01  4.925e-01]
 [-2.530e-01  6.380e-02 -3.481e-01  6.210e-02 -1.243e-01]
 [-6.320e-02 -5.303e-01 -2.412e-01 -5.300e-01  1.741e-01]
 [-1.897e-01 -1.771e-01  3.327e-01  3.562e-01 -2.037e-01]
 [-4.427e-01  7.940e-02 -2.226e-01 -3.090e-02  2.580e-01]
 [-5.692e-01 -1.720e-02 -1.288e-01 -3.200e-01 -5.368e-01]
 [-2.530e-01 -5.000e-04  3.695e-01  1.123e-01 -3.843e-01]
 [ 3.162e-01  2.095e-01 -3.760e-01 -1.479e-01 -3.043e-01]
 [ 2.530e-01 -5.779e-01  3.076e-01 -2.423e-01 -2.115e-01]]
[[ 0.  0.  0.  0.  0.]
 [ 0. -0. -0. -0.  0.]
 [ 0.  0.  0. -0. -0.]
 [ 0.  0. -0.  0.  0.]
 [ 0.  0.  0.  0. -0.]
 [ 0.  0. -0.  0.  0.]
 [ 0.  0.  0.  0. -0.]
 [ 0. -0. -0.  0.